apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sa-rbac-validator.fullname" . }}
rules:
  - apiGroups: 
      - "rbac.authorization.k8s.io"
    resources: 
      - roles 
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: 
      - "get"
      - "list"
      - "watch"
  - apiGroups: 
      - ""
    resources: 
      - namespaces
    verbs: 
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "authorization.k8s.io"
    resources:
      - tokenreviews
      - tokenrequests
    verbs:
      - create
    