apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sa-rbac-validator.fullname" . }}
  labels:
    app: {{ include "sa-rbac-validator.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "sa-rbac-validator.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "sa-rbac-validator.fullname" . }}
    spec:
      serviceAccountName: {{ include "sa-rbac-validator.fullname" . }}
      containers:
      - name: sa-rbac-validator
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.imageTag | default .Chart.AppVersion }}
        ports:
        - containerPort: 8443
        env:
          - name: SA_RBAC_VALIDATOR_SA_JSONPATH
            value: {{ .Values.saRbacValidator.saJsonPath }}
          - name: SA_RBAC_VALIDATOR_LOG_LEVEL
            value: {{ .Values.saRbacValidator.logLevel }}
          - name: SA_RBAC_VALIDATOR_SA_NOT_FOUND_BEHAVIOR
            value: {{ .Values.saRbacValidator.saNotFoundBehavior }}
        volumeMounts:
          - name: certs
            readOnly: true
            mountPath: /var/run/secrets/certs/
      volumes:
        - name: certs
          secret:
            secretName: {{ include "sa-rbac-validator.fullname" . }}
        