apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "sa-rbac-validator.fullname" . }}.flyingdogfood.github.com
webhooks:
- name: {{ include "sa-rbac-validator.fullname" . }}.flyingdogfood.github.com
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  sideEffects: None
  admissionReviewVersions: ["v1"]
  reinvocationPolicy: {{ .Values.webhook.reinvocationPolicy }}
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  clientConfig:
    caBundle: | {{ .Values.tls.crt | nindent 6 }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "sa-rbac-validator.fullname" . }}
      path: /validate
      port: 443
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: {{ .Values.webhook.apiGroups | toYaml | nindent 6 }}
    apiVersions: {{ .Values.webhook.apiVersions | toYaml | nindent 6 }}
    resources: {{ .Values.webhook.resources | toYaml | nindent 6 }}
    scope: {{ quote .Values.webhook.scope }}