webhook: 
  apiGroups: 
    - "apps"
  apiVersions: 
    - "v1"
  resources: 
    - "replicaSets"
  scope: "Namespaced"

saRbacValidator:
  saJsonPath: "/spec/template/spec/serviceAccountName"
  # Allow Request as if ServiceAccount is empty in ReplicaSet it is set in Pod
  saNotFoundBehavior: "allow"