webhook: 
  apiGroups: []
  apiVersions: []
  resources: []
  scope: ""
  failurePolicy: "Fail"
  reinvocationPolicy: "IfNeeded"
  timeoutSeconds: 10

deployment:
  replicas: 2
  image: flyingdogfood/sa-rbac-validator
  imageTag: 

saRbacValidator:
  saJsonPath: ""
  logLevel: "info"
  # Defines if the AdmissionReview should be denied or allowed if the ServiceAccount is not found under the specified JsonPath
  # Allowed values: deny, allow
  saNotFoundBehavior: "deny"

tls: 
  crt: ""
  key: ""
